server:
  port: 8081





spring:
  datasource:
    druid:
      url: jdbc:mysql://159.75.9.164:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Tiancai123
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PersonalBlog
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
    #host: 192.168.58.77

    #host: 192.168.123.224
    host: 127.0.0.1

  mail:
    host: smtp.qq.com
    username:
    password:
    port: 587


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: /var/log/myBlog/mybatis.log


